### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by digitaldangal** [joaocarmo/react-smart-data-table#1]
import SmartDataTable from 'react-smart-data-table'  when I add this this throws 

Uncaught SyntaxError: Unexpected token import

**Comment by joaocarmo** [comment]
@digitaldangal are you using webpack and is it properly configured with babel? Do you have **react-smart-data-table** installed in `node_modules/` and are you including that folder in your webpack configuration?
