### ISSUE TITLE
Problem with search function

### ISSUE THREAD

**Issue by vikrep** [joaocarmo/react-smart-data-table#11]
The problem with searching data in the table. If you do a pagination and try to make a search from the last page. The result is not displayed. Condition: per page of 10 lines, you are on the 10th page and you are searching for "Lo". A pagination is displayed, but not the result itself.

**Comment by vikrep** [comment]
Sorry, maybe it will help you ... I met such a problem in my project. After the search function, you should return the filtered result for render to a state with the page index 0.

**Comment by joaocarmo** [comment]
Of course, thank you for the tip! That's actually the solution I'm going to implement in the end, but I didn't do it when I added pagination because I thought it might be annoying to reset the page on every input change. Will need to test and see how it feels.

**Comment by joaocarmo** [comment]
@vikrep , I've released a new version (v0.5.10) that should fix this issue. Can you test?
