### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by webdevabhi** [joaocarmo/react-smart-data-table#12]
I have imported like
`import SmartDataTable from 'react-smart-data-table';`

then got error

`./node_modules/react-smart-data-table/lib/SmartDataTable.js
Module parse failed: Unexpected token (137:6)
You may need an appropriate loader to handle this file type.
|     }
|     return (
|       <i
|         className={`rsdt ${sortingIcon}`}
|         onClick={() => this.handleSortChange(column)}`

Please help with this.

**Comment by joaocarmo** [comment]
I accidentally pushed this with a bug. Thank you for letting me know, @webdevabhi !

I'll issue a fix today, but meanwhile try to use v.0.5.15 which is the same as v0.6.0, except for some props names that changed.

```
$ npm install react-smart-data-table@0.5.15
```

**Comment by webdevabhi** [comment]
I have done the same.

And one thing i need to ask you.

How to get action buttons in the table with onClick event.
Please help in this.

**Comment by joaocarmo** [comment]
For now, it's not possible to add custom content/elements to the table cells. What you can do is use the prop `onRowClick` to achieve an alternative. You can inspect the [example](https://github.com/joaocarmo/react-smart-data-table/blob/master/example/test.js). You can use it, for example to open a popup with the actions you need.

**Comment by webdevabhi** [comment]
Okay 
Thank You.

**Comment by joaocarmo** [comment]
I've issued a new version that should fix this issue, let me know if you find any other @webdevabhi !

**Comment by webdevabhi** [comment]
Thank You @joaocarmo
