### ISSUE TITLE
Something went wrong ! SyntaxError: unterminated character class

### ISSUE THREAD

**Issue by zedzone** [joaocarmo/react-smart-data-table#14]
Filtering causes the following error 
(Something went wrong ! SyntaxError: unterminated character class)
 if,  '(' or '[' is entered in filter input field. 

Escaping with '\' works, but then selection(coloring) wont work. Any work arounds, please.

And extremely thankful for react-smart-data-table. Really helpful.

**Comment by joaocarmo** [comment]
Thank you for alerting me to this bug, @zedzone ! The newly released version `0.6.6` addresses this issue.
