### ISSUE TITLE
Pagination customization/localization

### ISSUE THREAD

**Issue by guizmo** [joaocarmo/react-smart-data-table#15]
Hello, thanks for this nice component.
Will you consider adding some sort of customization for the "pagination" ? 
like localization or maybe simple arrows ?

Thanks again

**Comment by joaocarmo** [comment]
Hi @guizmo ! This is definitely on the to do list. I'm implementing a way in which a custom can be supplied to render the pagination, while the calculations are performed by the table component. I should be able to deploy it soon. Thank you for the feedback and I'll keep you posted.

**Comment by joaocarmo** [comment]
I just released `v0.7.0` which allows for a custom pagination component. Let me know if you find any issue with this. I also replaced the default pagination with a custom implementation.

**Comment by guizmo** [comment]
Sweet ! i'll check that out ASAP

**Comment by guizmo** [comment]
Works great, no bug.
I have reused your helper function and change few thing to use with reactstrap.
Thanks again !
