### ISSUE TITLE
Column ordering

### ISSUE THREAD

**Issue by pentolbakso** [joaocarmo/react-smart-data-table#16]
Hi.. thanks for this awesome component !

Btw, is there a way to order the columns ? Maybe we can add some sort of 'position' field in headers

**Comment by joaocarmo** [comment]
Hi @pentolbakso ! Thank you for you request, I believe this is an interesting feature to add to the component. Let's add it to the development.

**Comment by joaocarmo** [comment]
@pentolbakso , I've released this feature in the recent `0.7.2` version, if you want to try it out. Let me know of any issue you find.
