### ISSUE TITLE
Can't deploy to production with yarn build

### ISSUE THREAD

**Issue by DovRine** [joaocarmo/react-smart-data-table#17]
`yarn build`

yarn run v1.17.3
warning ../package.json: No license field
$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-smart-data-table/dist/react-smart-data-table.js:8:558 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by joaocarmo** [comment]
Just tested with the latest [create-react-app](https://github.com/facebook/create-react-app) and works as expected.
