### ISSUE TITLE
Custom headers not working

### ISSUE THREAD

**Issue by feudify** [joaocarmo/react-smart-data-table#18]
Hi,

Firstly, a fantastic module and very nearly perfect for my requirements but I am having an issue getting custom headers to display. It always displays the data set I am passing it (passed on as a prop from its parent from an axios request).

Here's a relevant snippet of my code:

const headers = {
      columnKey: {
        text: 'Id',
        invisible: true,
        sortable: false,
        filterable: false
      },
      columnKey: {
        text: 'Title',
        invisible: false,
        sortable: true,
        filterable: true
      },
      columnKey: {
        text: 'First Name',
        invisible: false,
        sortable: true,
        filterable: true
      },
      columnKey: {
        text: 'Last Name',
        invisible: false,
        sortable: true,
        filterable: true
      },
      columnKey: {
        text: 'Full Name',
        invisible: false,
        sortable: true,
        filterable: true
      },
      columnKey: {
        text: 'Post Code',
        invisible: false,
        sortable: true,
        filterable: true
      },
      columnKey: {
        text: 'Email',
        invisible: false,
        sortable: true,
        filterable: true
      },
      columnKey: {
        text: 'Unique Reference',
        invisible: false,
        sortable: true,
        filterable: true
      },
      tableActions: {
        text: 'Placeholder',
        invisible: false,
        transform: (value, index, row) => {
          return (
            <button onClick={() => console.log("the button worked")}>Show Details</button>
          )
        }
      }
    }

<SmartDataTable
        data={data}
        dataKey=''
        headers={headers}
        name='test-table'
        filterValue={filterValue}
        perPage={perPage}
        sortable
        withLinks
        withHeader
        loader={(
          <div className={sematicUI.loader}>
            Loading...
            </div>
        )}
      />

Many thanks in advance and keep up the great work!

**Comment by joaocarmo** [comment]
Hi @feudify ,

Can you please provide a sample of the data structure you are receiving from your http request? No need for values, just basic `data = [{ key: { nestedKey: 'String' } }]`.

**Comment by feudify** [comment]
Hi @joaocarmo ,

Thanks for the quick response.

Here you go:

[
    {
        "_id": "5d8118b18a9b5a76dc1a71ed",
        "title": null,
        "firstName": null,
        "lastName": null,
        "fullName": "sjcsd",
        "postCode": "sdsdcsdc",
        "email": null,
        "uniqueReference": "scsdcd",
        "placeholder": null
    }
]

**Comment by joaocarmo** [comment]
So I took your code and modified in a way that it should work.

Notice that you were not providing the correct keys to the `headers` object. You need to match the key in `headers` with the key in the data. If the objected is nested, then use a string and dot notation like `'key.nestedKey'`. Also, boolean values need no arguments and can be passed down implicitly, e.g. `withHeader`.

```javascript
const headers = {
  _id: {
    text: 'Id',
    invisible: true,
    sortable: false,
    filterable: false
  },
  title: {
    text: 'Title',
    invisible: false,
    sortable: true,
    filterable: true
  },
  firstName: {
    text: 'First Name',
    invisible: false,
    sortable: true,
    filterable: true
  },
  lastName: {
    text: 'Last Name',
    invisible: false,
    sortable: true,
    filterable: true
  },
  fullName: {
    text: 'Full Name',
    invisible: false,
    sortable: true,
    filterable: true
  },
  postCode: {
    text: 'Post Code',
    invisible: false,
    sortable: true,
    filterable: true
  },
  email: {
    text: 'Email',
    invisible: false,
    sortable: true,
    filterable: true
  },
  uniqueReference: {
    text: 'Unique Reference',
    invisible: false,
    sortable: true,
    filterable: true
  },
  placeholder: {
    text: 'Placeholder',
    invisible: false,
    transform: () => {
      return (
        <button onClick={() => console.log("the button worked")}>
          Show Details
        </button>
      )
    }
  }
}

<SmartDataTable
  data={data}
  headers={headers}
  name='test-table'
  filterValue={filterValue}
  perPage={perPage}
  sortable
  withLinks
  withHeader
  loader={(
    <div>Loading ...</div>
  )}
/>
```

**Comment by feudify** [comment]
Of course! Sorry, I was using your example as the basis of my code, completely forgetting it was a JS object and needed the proper key values and not "columnKey" as in your example!! 

Thank you so much!
