### ISSUE TITLE
Not fully compatible with Semantic UI's Pagination component

### ISSUE THREAD

**Issue by tisoap** [joaocarmo/react-smart-data-table#19]
Contrary to what [the documentation says](https://github.com/joaocarmo/react-smart-data-table#paginator), `react-smart-data-table` is not fully compatible with [Semantic UI's Pagination component](https://react.semantic-ui.com/addons/pagination/#types-pagination). Passing the default `Pagination` component directly to the `paginator` prop yields the following error in the browser console:

```
Warning: React does not recognize the `perPage` prop on a DOM element. If you
intentionally want it to appear in the DOM as a custom attribute, spell it as
lowercase `perpage` instead. If you accidentally passed it from a parent component,
remove it from the DOM element.
```

I've created a repository with a runnable example of this error [here](https://github.com/tisoap/data-table-test).

This happens because `react-smart-data-table` is passing down more props than necessary to the custom paginator component, and by default Semantic UI's Pagination is passing down those props to native DOM elements.

Edit: I [opened a PR](https://github.com/joaocarmo/react-smart-data-table/pull/20) with a proposed fix.

**Comment by joaocarmo** [comment]
@tisoap , thank you for your contribution. I've managed to successfully replicate the issue as described and I confirm that there is indeed a problem with passing extra props. Let me give a review and test of the PR https://github.com/joaocarmo/react-smart-data-table/pull/20 before merging into the master branch.

**Comment by joaocarmo** [comment]
This fix has been merged into the master branch and the changelog file has been updated as well.
