### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rogerthoang** [joaocarmo/react-smart-data-table#2]
ERROR in ./~/react-smart-data-table/lib/SmartDataTable.js
Module parse failed: C:\Project\Toro-Front-End\node_modules\react-smart-data-table\lib\SmartDataTable.js Unexpected token (114:6)
You may need an appropriate loader to handle this file type.
|     ) : 'rsdt-sortable-icon'
|     return (
|       <i className={'rsdt ' + sortingIcon} onClick={(e) => { this.handleSortChange(column) }} />
|     );
|   }
 @ ./~/react-smart-data-table/lib/index.js 2:0-45
 @ ./src/components/OrderManagementTable.js
 @ ./src/components/OrderManagement.js
 @ ./src/components/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://0.0.0.0:3000 webpack/hot/only-dev-server babel-polyfill whatwg-fetch ./src/index

**Comment by joaocarmo** [comment]
Make sure you have the proper react and babel modules to parse the JS syntax, including arrow functions.

**Comment by orion110217** [comment]
Hitting this error although I'm using arrow functions everywhere in my app and getting no errors.
