### ISSUE TITLE
Header columns trimming Integers from names

### ISSUE THREAD

**Issue by djsethi09** [joaocarmo/react-smart-data-table#22]
The keys in the object has the names such as "Last 1K P99 requests"

### Expected Behavior

The header should have "Last 1K P99 requests"

### Actual Behavior

"Last K P requests"

### Steps to Reproduce

Pass on the keys with Integers in the names

### Screenshot

![screenshot-localhost_3000-2020 03 20-14_13_47](https://user-images.githubusercontent.com/6747213/77148207-17d9dc80-6ab5-11ea-9cb3-8880ec66e0f8.png)

**Comment by joaocarmo** [comment]
Just confirmed the issue and the `parseDataForColumns()` function is responsible for this behaviour:

**Received**

```js
{
  key: 'last_1k_p99_requests',
  text: 'Last K P Requests',
  invisible: false,
  sortable: true,
  filterable: true
}
```

**Expected**

```js
{
  key: 'last_1k_p99_requests',
  text: 'Last 1K P99 Requests',
  invisible: false,
  sortable: true,
  filterable: true
}
```

I'll work on this and also add it as a sample in the tests.
