### ISSUE TITLE
Not displaying all the fields 

### ISSUE THREAD

**Issue by mullapu** [joaocarmo/react-smart-data-table#30]
if an API returns that a load with  multiple rows, let's say
row1: k1:v1,k2:v2,k3:v3
row2:k1:va1,k2:va2,k3:va3,k4:va4

in row K4 was empty so JSON did not return that key.
### Expected Behavior
the table should  be as 
____________________
| K1 | K2|  K3 |  K4|
-------------------
|V1 | V2 |.  V3 |.   |
------------------   
|Va1 | Va2 |Va3 |Va4   |

### Actual Behavior
instead, it only displays 3 columns ignoring 4th column since 1st row doesn't have it
| K1 | K2|  K3 |  
---------------
|V1 | V2 |.  V3 |
------------------   
|Va1 | Va2 |Va3 |

maybe it is only considering columns from 1st row only ignoring the rest

**Comment by mullapu** [comment]
Any alternative for the issue? :) i am running out of time and absolutely love the pkg.

**Comment by joaocarmo** [comment]
@mullapu the current behavior is to use the first row as a template, you are correct.

It's not practical to analyze all the rows for very large datasets (e.g., > 1000 rows) and find all the possible columns. Maybe we could add a larger or random sampling of a couple instead of only the first one. Will have to think about that.

Meanwhile, you can override some of the columns' behavior. The good news is you only need to manually add the ones that are missing, as mentioned in the `headers` section of the documentation [here](https://github.com/joaocarmo/react-smart-data-table#headers).

Try something like this:

```jsx
const extraHeaders = {
  K4: { // Your missing column's key
    text: 'K4 Column', // The display name
  },
}

const MyComponent = () => (
  <SmartDataTable
    data={data}
    name="my-table"
    headers={extraHeaders}
  />
)
```

**Comment by mullapu** [comment]
thanks for looking into it, I can't hardcode any headers because my JSON is dynamic.

**Comment by mullapu** [comment]
Also found columns are not in the same order  of as Json

**Comment by mullapu** [comment]
> @mullapu the current behavior is to use the first row as a template, you are correct.
> 
> It's not practical to analyze all the rows for very large datasets (e.g., > 1000 rows) and find all the possible columns. Maybe we could add a larger or random sampling of a couple instead of only the first one. Will have to think about that.
> 
> Meanwhile, you can override some of the columns' behavior. The good news is you only need to manually add the ones that are missing, as mentioned in the `headers` section of the documentation [here](https://github.com/joaocarmo/react-smart-data-table#headers).
> 
> Try something like this:
> 
> ```js-jsx
> const extraHeaders = {
>   K4: { // Your missing column's key
>     text: 'K4 Column', // The display name
>   },
> }
> 
> const MyComponent = () => (
>   <SmartDataTable
>     data={data}
>     name="my-table"
>     headers={extraHeaders}
>   />
> )
> ```

This didn't work, it is still considering data from 1st row ignoring the rest

**Comment by joaocarmo** [comment]
> thanks for looking into it, I can't hardcode any headers because my JSON is dynamic.

I could add a custom column resolver API and let the user provide its own logic, overriding the _first row_ logic.

> Also found columns are not in the same order of as Json

That's because JavaScript doesn't guarantee the transversal of objects keys will follow any particular order. You can read more about that in this [great comment](https://stackoverflow.com/a/30919039). That's why this package provides an `orderedHeaders` API in order for the user to guarantee a certain column order.

> This didn't work, it is still considering data from 1st row ignoring the rest

It's hard to understand without proper context.

**Comment by mullapu** [comment]
where I change to sample 150 records(large data set) rather than 1st record

**Comment by joaocarmo** [comment]
> This didn't work, it is still considering data from 1st row ignoring the rest

This forced me to investigate and found a bug with the `headers` parser. Will release a new version to fix this later today `v0.9.0`.

> Can you please point me to where I change to sample 150 records(large data set) rather than 1st record

I'm still thinking about this problem and will add a feature later to try and provide a solution for this kind of scenario.

**Comment by mullapu** [comment]
> > This didn't work, it is still considering data from 1st row ignoring the rest
> 
> This forced me to investigate and found a bug with the `headers` parser. Will release a new version to fix this later today `v0.9.0` [#33].
> 
> > Can you please point me to where I change to sample 150 records(large data set) rather than 1st record
> 
> I'm still thinking about this problem and will add a feature later to try and provide a solution for this kind of scenario.

I working on a workaround to sort data with null in the end so that JSON with max fields comes to the front of the array.

**Comment by mullapu** [comment]
It worked. <br>
`data.sort(function (a, b) { 
      return (b._fieldname_ != null) - (a._fieldname_ != null) || 
        a._fieldname_ - b._fieldname_; 
    })`

**Comment by joaocarmo** [comment]
@mullapu , great that you've found a solution albeit not an optimal one. Try and see if the new version `v0.9.0` works for you through the solution I provided earlier (`headers` prop).

I'll keep this issue open as I think of a proper way to overcome this kind of dynamic scenario.

**Comment by mullapu** [comment]
one quick question how do I pass headers and auth keys when using async loading

**Comment by joaocarmo** [comment]
Good question, @mullapu ! That is something currently not available.

You can try and use something like [fetch-intercept](https://github.com/werk85/fetch-intercept), but I'll have to add custom fetch options to the features.

**Comment by joaocarmo** [comment]
@mullapu , you can now pass Fetch API `options` using the `dataRequestOptions ` prop in `v0.10.0`. For this particular case, you'll want to pass `{ headers: { /* ... */ } }`.

**Comment by mullapu** [comment]
> @mullapu , you can now pass Fetch API `options` using the `dataRequestOptions ` prop in `v0.10.0`. For this particular case, you'll want to pass `{ headers: { /* ... */ } }`.

Thank you, for the quick turnaround. I will try it and let you know.

**Comment by joaocarmo** [comment]
@mullapu, `v0.12.0` adds a `dataSampling` prop which you can use to resolve the initial issue.

If the data is completely unpredictable, just set it to `100` and it will always sample the whole data set.

**Please note:** this might be _slow_ depending on the amount of data.
