### ISSUE TITLE
Not paginating properly

### ISSUE THREAD

**Issue by jesulopez** [joaocarmo/react-smart-data-table#36]
### Problem
I'm trying to use the autopaginator using the "perPage" property, the paginator appears and it modifies the number of pages depending on the total number of results, but the first page shows all the rows and when you click on the next page it never change because all the rows are in the first page.

### Expected Behavior

I expect it to show 2 pages with 5 rows per page, and when I click on next page It shows the other 5 remaining

### Actual Behavior

It shows 2 pages but in the first page there are all the the rows (10 rows). And it shoulds only show 5 per page.

### Steps to Reproduce

`<SmartDataTable
            data="https://jsonplaceholder.typicode.com/users"
            dataKey=""
            name="test-table"
            className="ui compact selectable table"
            perPage='5'
       />`

### Screenshot

![image](https://user-images.githubusercontent.com/3225959/111994869-95955580-8b18-11eb-93a0-acf8a05cdf2d.png)

### Your Environment

When I installed via NPM I have to force it because I'm using react 17.0.1 and It needs the dependency ^16.8.0

**Comment by joaocarmo** [comment]
@jesulopez, the problem is that you're passing `'5'` as **string** and the `perPage` expects a **number**. Simply remove the quotes and it should work as expected.

```jsx
// e.g.,
<SmartDataTable
  data="https://jsonplaceholder.typicode.com/users"
  dataKey=""
  name="test-table"
  className="ui compact selectable table"
  perPage={5}
/>

Thank you for the tip about the required version, I will update that.
```
