### ISSUE TITLE
Displaying duplicate columns when using 'header' props

### ISSUE THREAD

**Issue by dmtapia** [joaocarmo/react-smart-data-table#39]
### Expected Behavior

When using props 'headers' to override a column's header name, it should only change the name of the header.

### Actual Behavior

It creates a duplicate of that same column. (See CO2 Reduced in attached photo)

### Screenshot

<img width="1133" alt="Screen Shot 2021-04-13 at 11 16 12 PM" src="https://user-images.githubusercontent.com/21189983/114686452-7ec4c780-9cae-11eb-8db9-2cc88f6fe328.png">

### Edit

Getting this error: 

> Encountered two children with the same key, `cO2Redcued`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

PS. The entire team really likes your table, btw! We're using it for a class project and it really helped save us some time. Thank you!!

**Comment by joaocarmo** [comment]
@dmtapia, it's really good to know you and your team like this project!

Can you tell me which version are you currently using?

**Comment by joaocarmo** [comment]
Nevermind. I was able to replicate the issue using the latest version.

I added a fix in `v0.11.0`. Try it out and let me know if you find something amiss.
