### ISSUE TITLE
Error - need an appropriate loader

### ISSUE THREAD

**Issue by c0debreaker** [joaocarmo/react-smart-data-table#4]
https://imgur.com/a/GAig8

Failed to compile.

./node_modules/react-smart-data-table/lib/SmartDataTable.js
Module parse failed: Unexpected token (114:6)
You may need an appropriate loader to handle this file type.
|     ) : 'rsdt-sortable-icon'
|     return (
|       <i className={'rsdt ' + sortingIcon} onClick={(e) => { this.handleSortChange(column) }} />
|     );
|   }

**Comment by tbrooke** [comment]
Why is this Invalid I have the same issue:

./node_modules/react-smart-data-table/lib/SmartDataTable.js
Module parse failed: Unexpected token (114:6)
You may need an appropriate loader to handle this file type.
|     ) : 'rsdt-sortable-icon'
|     return (
|       <i className={'rsdt ' + sortingIcon} onClick={(e) => { this.handleSortChange(column) }} />
|     );
|   }

**Comment by joaocarmo** [comment]
Hi @tbrooke , please check [my comment](https://github.com/joaocarmo/react-smart-data-table/issues/6#issuecomment-377923017) in issue #6 .
