### ISSUE TITLE
Error using with webpack

### ISSUE THREAD

**Issue by SathishRaju** [joaocarmo/react-smart-data-table#6]
Got this error when trying to use with webpack

ERROR in ./node_modules/react-smart-data-table/lib/SmartDataTable.js
Module parse failed: Unexpected token (114:6)
You may need an appropriate loader to handle this file type.
|     ) : 'rsdt-sortable-icon'
|     return (
|       <i className={'rsdt ' + sortingIcon} onClick={(e) => { this.handleSortChange(column) }} />
|     );
|   }
 @ ./node_modules/react-smart-data-table/lib/index.js 2:0-45

**Comment by dhcloud** [comment]
Same problem I have on a webpack build, has this been resolved?

**Comment by kkgujjar** [comment]
same problem here ... :(

**Comment by DZcoderX** [comment]
Same problem...

**Comment by joaocarmo** [comment]
This is the first time an arrow function appears in the code, so I believe it may be related to that. Please make sure your _webpack_ configuration is including: _babel-core_, _babel-loader_, _babel-preset-env_ and _babel-preset-react_.

These are dev dependencies and will not be included by default when running _npm install <package>_.

You can check the _webpack_ configuration on this repository for examples.
